version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  ticket-service:
    build: ./ticket-service
    ports:
      - '4001:4001'
    environment:
      - PORT=4001
      - MONGO_URI=mongodb://mongo:27017/ticketdb
    depends_on:
      - mongo

  event-service:
    build: ./event-service
    ports:
      - '4002:4002'
    environment:
      - PORT=4002
      - MONGO_URI=mongodb://mongo:27017/eventdb
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - '4003:4003'
    environment:
      - PORT=4003
      - MONGO_URI=mongodb://mongo:27017/orderdb
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo

  payment-service:
    build: ./payment-service
    ports:
      - '4004:4004'
    environment:
      - PORT=4004
      - MONGO_URI=mongodb://mongo:27017/paymentdb
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    ports:
      - '4005:4005'
    environment:
      - PORT=4005
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo

volumes:
  mongo-data:
